# Build details of yawl services
yawl.service.version=6.0
yawl.service.build=${yawl.build.number}
yawl.service.build.date=${yawl.build.date}

resource.service.version=6.0
resource.service.build=${resourceService.build.number}
resource.service.build.date=${resourceService.build.date}

worklet.service.version=6.0
worklet.service.build=${workletService.build.number}
worklet.service.build.date=${workletService.build.date}

mail.service.version=6.0
mail.service.build=${mailService.build.number}
mail.service.build.date=${mailService.build.date}

docstore.service.version=6.0
docstore.service.build=${documentStore.build.number}
docstore.service.build.date=${documentStore.build.date}

ui.service.version=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}
ui.service.build=${parsedVersion.nextIncrementalVersion}
ui.service.build.date=${timestamp} (UTC)

vaadin.version=${vaadin.version}

