package org.yawlfoundation.yawl.ui.view;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Michael Adams
 * @date 3/11/2025
 */
public enum LogViewType {
    SpecificationIds ("Specification IDs",
            "The identifiers of every logged specification instance"),
    Specification ("Specification Events",
            "All case events for a selected specification and version (can export as XES)"),
    SpecificationAllVersions ( "Specification Events (All Versions)",
            "All case events for all versions of the selected specification (can export as XES)"),
    SpecificationStatistics ("Specification Statistics",
            "Gather some statistics for a selected specification"),
    ParticipantHistory ("Participant History",
            "All events generated by a selected participant" ),
    CaseEvents ("Case Events", "All events for a selected case"),
    CasesInvolvingParticipant ("Cases Involving Participant",
            "All case events for all cases involving a selected participant" )
 //   TaskStatistics ("Task Statistics", "to do")
    ;

    public final String _shortText;
    public final String _description;

    public final List<String> shortTextList = new ArrayList<>();


    LogViewType(String text, String desc) {
        _shortText = text;
        shortTextList.add(_shortText);
        _description = desc;
    }


    public String shortText() { return _shortText; }

    public String description() { return _description; }

}
